### ISSUE TITLE
No clear resolution to token:generate error

### ISSUE THREAD

**Issue by ibraheemk** [relaypro/relay-cli#12]
When attempting to generate a token, if the user forgot to check the 'remember me' box, there is no guidance provided on how to resolve. 

In addition, if the user attempts to logout to manually set the 'remember me' box, using `relay logout` does not result in the user actually logging out.

**Comment by BrandonSmith** [comment]
Improved the `login`, `logout`, and `token:generate` behavior.

* Now, the CLI will requires the user to successfully log in with a refresh token. If "remember me" is not checked, and no refresh token returned, the `login` and `token:generate` will provide steps to fully log out and attempt log in again.
* `logout` prompts the user to fully log out by visiting the logout url.
