### ISSUE TITLE
Support for triple and quintuple tap triggers

### ISSUE THREAD

**Issue by ibraheemk** [relaypro/relay-cli#4]
Add support for triple and quintuple tap triggers to workflow:create:button CLI command.

**Comment by ibraheemk** [comment]
Actions to add: 
action_button_triple_tap
action_button_quintuple_tap 

Example: 
type TapType = `action_button_single_tap` | `action_button_double_tap` | `action_button_triple_tap`

relay workflow:create:button -n hello -u relay-local://hello_world --trigger=triple -a greeting=hello 990007560008523
=== Installed Workflow
ID                      Name  Type          Uri                       Args                    Installed on
L7VgN4Dlii542Zw5aSe9CEC hello button:triple relay-local://hello_world greeting=hello | string

**Comment by BrandonSmith** [comment]
@ibraheemk I can see through triple in the near term. However, ibot only supports single, double, and triple.

**Comment by ibraheemk** [comment]
@BrandonSmith Sounds good, triple only is good for now 👍🏾

**Comment by BrandonSmith** [comment]
Closing this issue as invalid. If a future need for triple and quadruple button tap becomes evident, we will investigate again.
