### ISSUE TITLE
Upon server error, CLI masks that and says "Super constructor may only be called once"

### ISSUE THREAD

**Issue by cmarcelk** [relaypro/relay-cli#5]
As a separate issue, when I try to create a workflow the server is returning an error. However for this ticket, it appears that the CLI is masking that server error and instead returning the message "Super constructor may only be called once". I would expect the CLI to indicate that there was a server error.

```
mkinard@mkinard-pc:~$ relay workflow:create:phrase --name=hellophrase --uri=wss://redacted.herokuapp.com --trigger="hello"
    ReferenceError: Super constructor may only be called once
mkinard@mkinard-pc:~$ relay --version
@relaypro/cli/0.2.1 linux-x64 node-v16.13.2

```

**Comment by BrandonSmith** [comment]
Closed with commit 7e12f0d74f7016e411ae3dbe9cf5c2c4a93b7184
