### ISSUE TITLE
error when creating a workflow with a phrase trigger

### ISSUE THREAD

**Issue by cmarcelk** [relaypro/relay-cli#6]
The following command is returning an error from the server:
relay workflow:create:phrase --name=hellophrase --uri=wss://redacted.herokuapp.com --trigger="hello"

Working with the server team they noticed an unexpected inbound payload from the CLI. What they are seeing is (focusing just on the trigger phrase):
`,"on_phrase":["hello"]}`
but they are expecting
`,"on_phrase":"hello"}`
or
`,"on_phrases":["hello"]}`

So in the server the payload is failing the JSON validation.

**Comment by BrandonSmith** [comment]
Closed by #11
