### ISSUE TITLE
point CLI to prod-env by default

### ISSUE THREAD

**Issue by cmarcelk** [relaypro/relay-cli#8]
With a pending move from the api-env to prod-env, the CLI should default to being in prod-env, with a way to override/set that to be api-env as needed.

**Comment by cmarcelk** [comment]
Should defer work on this until we're ready to start putting new users in prod-env.

**Comment by BrandonSmith** [comment]
On next release the following environment variable can be set to access production:

```
RELAY_ENV=pro relay [command]
```

Of course, users can export this in their shell profile:

```.profile
export RELAY_ENV=pro
```

**Comment by ibraheemk** [comment]
This is fixed in the latest version of the CLI
